### ISSUE TITLE
Thread-safety of TelegramLongPollingBot

### ISSUE THREAD

**Issue by marcluque** [rubenlagus/TelegramBots#1162]
I have searched the open and closed issues and the wiki but couldn't find any information on thread-safety.
My question/concern is whether an instance of `TelegramLongPollingBot` can be used by several threads concurrently?
What about other "bot types"? E.g., the one for webhooks.

**Comment by Chase22** [comment]
Short answer: yes

Long answer:
The library is currently build so that the BotClass is the one to rule them all. Basically: AbsSender (a superclass of all bot classes) is the one implementing the execute method. It does not have any state and send all requests to telegram. The LongPolling/Webhook bot implement the update gathering. This update gathering is technically not thread safe, but you will not interact with it. We are working on splitting some components into separate objects to make this more transparent
