### ISSUE TITLE
send photos

### ISSUE THREAD

**Issue by TheBouwman** [rubenlagus/TelegramBots#17]
How are you able to send photos?

**Comment by Clevero** [comment]
It's easy as the following

In thisexample I want to send my user the [Wikimedia Commons Picture og the Day](https://commons.wikimedia.org/w/api.php?action=featuredfeed&feed=potd&feedformat=rss&language=en) right after, he sent me `/wiki`

The code could look like this:

```
@Override
	public void onUpdateReceived(Update update) {
		
		//check if the update has a message
		if(update.hasMessage()){
			Message message = update.getMessage();
			
			//check if the message has text. it could also  contain for example a location ( message.hasLocation() )
			if(message.hasText()){
				
				if(message.getText().equals("/wiki")){
				
					SendPhoto sendPhotoRequest = new SendPhoto();
					sendPhotoRequest.setChatId(message.getChatId().toString());
					
					
													//path: String, 					photoName: String
					sendPhotoRequest.setNewPhoto("/home/marcel/Downloads/potd_wikipedia.jpg", "Good Friday.jpg"); //
					try {
						sendPhoto(sendPhotoRequest);
					} catch (TelegramApiException e) {
						/*
						 * Do some error handling
						 * e.printStackTrace();
						 */
					}//end catch()

				}//end if()
				
			}//end if()
		}//end if()
		
	}//end onUpdateReceived()
```

This method uploads the photo every time the user send the bot `/wiki`. Telegram stores the files we upload on their server. And if next time someone wants to retrieve THE SAME photo we uploaded some time ago, you should use instead of `SendPhoto.setNewPhoto()` the `SendPhoto.setPhoto()` method. This method has just one parameter, file_id. 

[link to sendPhoto in the Bot API](https://core.telegram.org/bots/api#sendphoto)

**Comment by TheBouwman** [comment]
How do you save the image that you receive?

**Comment by Clevero** [comment]
this was also asked in #16

**Comment by orasonoalladucati** [comment]
Hi, i don't understand one thing:
the path of the file to upload is the path on my filesystem?if not, what is it?

**Comment by Clevero** [comment]
jape, `path` is the place where your photo is located on your filesystem. the library pick it up, uploads it, and so on...

In my example above the file was in `/home/marcel/Downloads/potd_wikipedia.jpg`

**Comment by rubenlagus** [comment]
@orasonoalladucati As @Clevero said, you only need to provide the path to the file (where the file is located in your pc) and the api will upload it. Does this solve the problem?

**Comment by MetaiR** [comment]
@rubenlagus 
hi,
I sent some uncompress photos, so they type became `Document`. the problem is after a while sending them using `document_id` won't work anymore unless I manually upload or forward those picture to bot again
I read telegram docs and it seems to me, they have expiration limits (about 1 hour)
so what should I do?
