### ISSUE TITLE
problem with Keyboards

### ISSUE THREAD

**Issue by mbarzegar93** [rubenlagus/TelegramBots#182]
hi
how can i create Keyboard for my bot?
can someone simply explain it to me, i read the code example that are here but i didn't understand them and i google it and the tutorials are in php and i cant figure it out,i use telegram api doc and i cant understand it,there is no example in api doc
please someone simply tell me how i can create a keyboard for my bot? thanks

**Comment by Clevero** [comment]
Did you read the wiki?

if you mean with "code example" the [TelegramBotsExample](https://github.com/rubenlagus/TelegramBotsExample) repo and not the wiki -> Always read the [wiki](https://github.com/rubenlagus/TelegramBots/wiki/FAQ#how-to-use-custom-keyboards)! ;) There there a deeper instructions available, among others also for custom keyboards.

Maybe to give a specific bot example out of the mentioned example repo, @weatherbot](https://telegram.me/weatherbot) should contain helpful code. If you have any further questions, feel free to ask or to join our [group chat](https://telegram.me/JavaBotsApi) on Telegram itself (please keep always the rules in the group description in mind)

If not, please tell us what exactly you don't understand in the current explanations, so that we can solve your issues.

**Comment by mbarzegar93** [comment]
yes i mean the code example in [TelegramBotsExample](https://github.com/rubenlagus/TelegramBotsExample)
tnks for wiki link,for now i stick to it
and for the group chat telegram say the user @javabotsapi not found!
i cant join group chat

**Comment by Clevero** [comment]
Mhmhm, I've tested the link. Works fine on my Android Device. Anyway, you should find the link also in the README 

Is your problem now solved? Can this issue be closed?

**Comment by mbarzegar93** [comment]
yes close it
thanks for the help
