### ISSUE TITLE
A way to change telegram endpoint

### ISSUE THREAD

**Issue by matiniamirhossein** [rubenlagus/TelegramBots#226]
Hello
Is there any method to change api endpoint to somewhere else without compiling the project again?

Regards.

**Comment by rubenlagus** [comment]
What do you mean?

**Comment by matiniamirhossein** [comment]
https://pwrtelegram.xyz/
https://api.pwrtelegram.xyz/bot<token>
instead of 
https://api.telegram.org/bot<token>

**Comment by rubenlagus** [comment]
Haven't think about it, maybe you can overwrite something; but I'm not sure if it will even work exactly like the real api.

In any case, I'm not changing the library in order to support some random server that no one knows what is doing with the information, I trust Telegram servers, but I don't trust third party servers that much.

**Comment by matiniamirhossein** [comment]
I totally accept your answer.
Just wanted to recheck before recompiling your project.
It's an open source library which allows us to send and receive files to telegram up to 1.5GB. Default limit is 50MB max.
Also it's library is open source: https://github.com/pwrtelegram/pwrtelegram-backend
I copied that project and modified some files and put that to wamp server on my local server (windows) in 127.0.0.1 so now I will change api endpoint to 127.0.0.1/botTOKEN.

Thanks for your answer.

**Comment by rubenlagus** [comment]
You may be able to make this change easily in next upcoming version
