### ISSUE TITLE
get bot username with token?

### ISSUE THREAD

**Issue by Pie133** [rubenlagus/TelegramBots#231]
Hi
i want to know is this possible to get bot username with token ?

**Comment by Clevero** [comment]
What do you mean exactly?

In your application, there should be a `getBotToken()` and `getBotUsername()` method. The first one is required in order to run your bot. The second one can be helpful.

Another way to get the bot username would be [getMe](https://core.telegram.org/bots/api#getme) in the API. You can call getMe like all other functions of the Bot API, cause it's just a implementation of the offical Telegram Bot API.

```java
try{
            User me = getMe();
            System.out.println("id: " + me.getId());
            System.out.println("firstName: " + me.getFirstName());
            /*
             * and
             * so
             * on
             * ...
             */
            
        }
        catch(TelegramApiException e){
            e.printStackTrace();
        }

```

Hope this helps

**Comment by Pie133** [comment]
i mean is there any function that i can insert the bot token and get bot username
something like this:
getBotUsernameFromToken("1234456:dfgsdkjgkuygkuyKHYKGygluhlyuy");
and then it return something like : @testbot

**Comment by Clevero** [comment]
Yes, getMe would be it.

The [API doc](https://core.telegram.org/bots/api#getme) states about getMe:
`A simple method for testing your bot's auth token. Requires no parameters. Returns basic information about the bot in form of a User object.`

And "...basic information about the bot..." includes also the botusername as stated above.

**Comment by Pie133** [comment]
I love you man :D

**Comment by dapoldi** [comment]
The flirting is strong with this one.


-------- Original message --------
