### ISSUE TITLE
Why User object's id has Integer datatype, but a Chat object has Long ?

### ISSUE THREAD

**Issue by no-nevis** [rubenlagus/TelegramBots#295]
an Integer stores 32 bytes and user ids are chat ids and they're 53 bytes long (referring to telegram docs), so why using an Integer for User object, while a Chat have a Long id type ?

**Comment by rubenlagus** [comment]
[User_id](https://core.telegram.org/bots/api#user) -> **Unique identifier for this user or bot**
[Chat_id](https://core.telegram.org/bots/api#chat) -> **Unique identifier for this chat. This number may be greater than 32 bits and some programming languages may have difficulty/silent defects in interpreting it. But it is smaller than 52 bits, so a signed 64 bit integer or double-precision float type are safe for storing this identifier.**

As you see, they just follow Telegram docs.

**Comment by no-nevis** [comment]
Yes they do, but I'm sure they forgot to add the documentation to user id and also user ids are chat ids; because I saw ids like 3742036475 which is obviously bigger than integer's range: 2147483647

**Comment by no-nevis** [comment]
Wrong button -_-

**Comment by rubenlagus** [comment]
I have never seen an user_id that doesn't fit in an integer. And yes, user_ids can be chat_ids, but it doesn't mean that the field for the user_id will need to store the value of every chat_id.

In any case, as soon as they update the api docs showing that they could be higher, I'll update it.

And, finally, I hope they don't have any user_id with a value bigger than int32, otherwise official Android app will also stop working right away.

**Comment by no-nevis** [comment]
That was a mistake by me, I just read one digit more :D
