### ISSUE TITLE
Cannot set in InlineKeyboardButton (url field) value: http://localhost:8080/scheduler

### ISSUE THREAD

**Issue by dinarAkv** [rubenlagus/TelegramBots#302]
I want to test my **InlineKeyboardButton** in localhost, but when I set in field **url** value "http://localhost:8080/scheduler" I get error **Bad Request: BUTTON_URL_INVALID**. 

I noticed that urls that don't have point symbol (".") in host not except and throw exception above.
For example this url in **InlineKeyboardButton** work fine:
http://scheduler.com

But this url throw exception (without "." symbol in host): http://schedulercom

I think it doesn't make sense to fail urls without "." symbol in host.

**Comment by Fotomultman** [comment]
Have the same problem

**Comment by Clevero** [comment]
Don't have checked the code yet, but I think it should be a "limitation" of the Bots API rather than in the lib.

Possible workaround?:
Why not change localhost to localhost.localdomain?

You would need to change your hosts file (tested it under Linux and Windows 10), that localhost.localdomain is pointing to your localhost address

For example under most Linux distros, edit the file ```/etc/hosts``` where as under Windows 10 it should be ```C:\Windows\System32\Drivers\etc\hosts```

Regardless of the file location, add the following lines to your hosts file:
```127.0.0.1 localhost.localdomain localhost```

After that, test it while we ping our new localhost address
![poiugzu](https://user-images.githubusercontent.com/6106081/30453344-e7bb2bb6-9998-11e7-85c4-9bc2a992ae57.PNG)

Would be nice if you could give feedback to this possile workaround for you

**Comment by dinarAkv** [comment]
Thank you, **Clevero**. You suggest awesome idea and it work perfectly. I add to hosts (in windows) file the row **127.0.0.1       localhost.localdomain** and after that my url  **http://localhost.localdomain:8080/scheduler** work without error.
