### ISSUE TITLE
How to access silent variable in AbilityExtension-implemented class?

### ISSUE THREAD

**Issue by andriihorpenko** [rubenlagus/TelegramBots#721]
As far as I understand, `silent` is available in the scope of `AbilityBot` class. When I implement AbilityExtension interface there's no `silent` variable so the compilation fails. Should I pass something to the `AbilityExtension` method registration? By method registration I mean the following:
Bot:
```java
// constructor, creator_id, etc

public AbilityExtension analyseNewMember() {
    return new AnalyseNewMember();
}
```
AnalyseNewMember:
```java
public class AnalyseNewMember implements AbilityExtension {
    public Ability handle() {
        return Ability
                .builder()
                .name("test")
                .locality(ALL)
                .privacy(PUBLIC)
                .action(ctx -> silent.send("This is a test message.", ctx.chatId())); // silent is not recognized
    }
}
```

**Comment by kortov** [comment]
It's a good point. I guess the doc in wiki isn't right [wiki](https://github.com/rubenlagus/TelegramBots/wiki/Ability-Extensions). And for an access to a `silent` you need to pass it as a method variable or through propety in the `AnalyseNewMember` class

**Comment by andriihorpenko** [comment]
Yeah, example code in Wiki may confuse some people. Thanks for a recommendation anyway!

**Comment by kortov** [comment]
You're welcome :) Actually, I didn't use use such approach but I guess, there is even no point to to pass `silent` as a method parameter. Because the implementation works like : scan the package with reflection , find classes which have methods which return `Ability`, elaborate on it's filters, put it into a collection of bot's methods and save it into collection.Then when the message to the bot met conditions, the method is invoked. I guess it works likes this as I understand it

**Comment by andriihorpenko** [comment]
What I did is passed `this` to the `AnalyseNewMember` class constructor and it worked like a charm🤷🏻‍♂️

**Comment by addo37** [comment]
That needs to be updated in the wiki for sure. I'll update this soon.

**Comment by romangraef** [comment]
I actually forgot about this. When I first implemented this i just made it work (TM) for my specific use case, which actually didn't post back to telegram. The problem with supplying the silent object is that AbilityExtension is in fact an interface, so that won't work. It also doesn't recursively search for new extensions, which might also be an unexpected flaw/behaviour.
