### ISSUE TITLE
"Could not create SSL/TLS secure channel" only on windows 7

### ISSUE THREAD

**Issue by dotmax** [rubenlagus/TelegramBots#724]
Hi, did someone notice the same problem? 
starting from today a HttpWebRequest (post) to https://api.telegram.org/bot<TOKEN>/getme
on win7 fails with error "Could not create SSL/TLS secure channel"
already tried with ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
On windows 7/2008R2 i get this error, the same code on windows 10 works as expected.

**Comment by amoamare** [comment]
Getting the same issue now Windows Server 2012 R2 - Version 6.3 (Build 9600)
I ensured Tls12 and 1.3 enabled, I even tried just enabling all of them. Even ensured the power shell has full Tls12 and 1.3 enabled using the command [System.Net.ServicePointManager]::SecurityProtocol

![image](https://user-images.githubusercontent.com/15149902/73960495-423a5680-48c8-11ea-8e26-9c626237c4c5.png)

![image](https://user-images.githubusercontent.com/15149902/73960679-92b1b400-48c8-11ea-852b-8214b9cbcd57.png)

Just for testing in the I added the following to ensure as well. 

 ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls13;

Created my own httpClient to pass to the bot, nothing works. Continuously getting this error since 
2/5/2020 at approx 11:00PM MST

**Comment by amoamare** [comment]
To add, there was no changes to my server when this happened this was a clear change on Telegram's side that caused this issue to arise. I did update my server after this to that build 9600 however it was doing this prior to any updates or changes to my server. (It has been unchanged for 65 days, no updates, not patch installs etc)

**Comment by dapoldi** [comment]
Guys, see @botnews, < TLS1.2 is no longer supported so that’s quite likely your issue, given the platforms mentioned.
Marv



Op 5 feb. 2020 om 23:07 heeft dotmax <notifications@github.com> het volgende geschreven:

﻿

Hi, did someone notice the same problem?
starting from today a HttpWebRequest (post) to https://api.telegram.org/bot<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.telegram.org%2Fbot&data=02%7C01%7C%7C31dd484ed93341e4e6d308d7aa87d9bd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637165372752823010&sdata=r11zorFEAn85mmpmal%2BupUe5gbP1COvbo5%2BUglkLcKI%3D&reserved=0>/getme
on win7 fails with error "Could not create SSL/TLS secure channel"
already tried with ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
On windows 7/2008R2 i get this error, the same code on windows 10 works as expected.

**Comment by dapoldi** [comment]
Hey there, have a look @botnews, < TLS1.2 is no longer supported, given the platforms mentioned that’s quite likely your issue.

**Comment by dotmax** [comment]
I managed to solve the problem (it was a missing cipher suite)
Details here:
https://www.reddit.com/r/Telegram/comments/ezhfau/bot_stops_working_on_windows_7_c/
