### ISSUE TITLE
Make top of group members

### ISSUE THREAD

**Issue by khanZhomart** [rubenlagus/TelegramBots#845]
Hello, my Telegram bot analyzes messages for abusive words and outputs short phrase for it, if success. 

So I want to count every user's messages in group chat, which contain abusive words and make a top-5 from them. Can you give some ideas how to implement it?

**Comment by Chase22** [comment]
The start is pretty much always the same. You get a message and analyze it for the words you want to block. After that happened you have 2 options:

**Save the entire metadata of the message**
You could save the entire metadata, like time send, originated user, chat, blocked word, message text etc. This allows you more flexible generation of your top-5 in the future, you could for example decide in the future to count the number of blocked words instead of the number of messages, you could also have messages only be counted for a certain timeframe, discarding messages that are older than x weeks.

This takes more storage space and also takes more processing power since you'll have to calculate the top-5 on every request. But it allows you to be much more flexible in how to generate the score, even allowing the group admin to configure how the score is calculated.

**Save the current score**
Only save a score for the current user and incrementing it when a message with a banned word is received. This doesn't allow any flexibility and will cause bad data when you change the scoring system. But is much easier to implement and more storage efficient.

Personally i'd recommend you go with the metadata aproach, while taking up a more storage space, it's still easily handeled and allows you to be much more flexible in the score calculation
